version: '3'

services:
    app:
      build:
        context: ./app
        dockerfile: Dockerfile
      container_name: nodejs
      working_dir: /app
      volumes: 
        - ./app:/app
      networks:
        - net01
      tty: true
      entrypoint:  dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && npm start"


    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: mysql
      restart: always
      tty: true
      environment:
        - MYSQL_DATABASE=app
        - MYSQL_ROOT_PASSWORD=mysuperpass
      networks:
        - net01
    
    web:
        build:
          context: ./web
          dockerfile: Dockerfile
        container_name: nginx
        networks:
          - net01
        ports:
          -   "8080:80"

networks: 
    net01:
        driver: bridge

  
